// The four sections from docs/Instructions.md. Each owner replaces their placeholder screen.
export const SECTIONS = [
  {
    to: '/discover',
    icon: 'search',
    title: 'Discover & browse',
    summary: 'Find meals nearby, sorted by evidence and recency',
    owner: 'Person A',
    branch: 'feature/discover-browse',
    planned: [
      'Onboarding',
      'Set location / search',
      'Restaurant list',
      'Meal list',
      'Filters and sort (evidence strength, recency, distance)',
    ],
    insight: 'Pyper wanted sorting by verification strength and recency.',
  },
  {
    to: '/meals',
    icon: 'meal',
    title: 'Meal trust detail',
    summary: 'How a dish was checked, when, and by whom',
    owner: 'Person B',
    branch: 'feature/meal-trust-detail',
    planned: [
      'Meal detail',
      'Precaution badges (dedicated fryer, glove changes…)',
      'Last verified date and history',
      'Reports with reviewer type shown inline',
    ],
    insight: 'The core value proposition: confidence in every meal.',
  },
  {
    to: '/contribute',
    icon: 'plus',
    title: 'Contribute & verify',
    summary: 'Submit a report, call ahead, peer review',
    owner: 'Person C',
    branch: 'feature/contribute-verify',
    planned: [
      'Submit a report',
      'Call-ahead script and checklist',
      'Become a verifier',
      'Peer review and conflicts (pending → confirmed)',
    ],
    insight: "Alondra's peer-review model; Mallory would rather be told there's a risk than have someone guess.",
  },
  {
    to: '/account',
    icon: 'person',
    title: 'Account & community',
    summary: 'Your reviewer type, saved places, help',
    owner: 'Person D',
    branch: 'feature/account-community',
    planned: [
      'Profile setup (Celiac / Strict GF / Gluten-sensitive)',
      'Saved restaurants',
      'Community',
      'Settings',
      'Help / FAQ',
    ],
    insight: "Pyper's distrust of non-celiac reviewers; the community-support theme.",
  },
]
